joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
teleop_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 0.4
      y: 0.4
    scale_linear_turbo:
      x: 0.8293
      y: 0.8293

    axis_angular:  # Right thumb stick horizontal
      yaw: 3        
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 2.5

    require_enable_button: true
    enable_button: 4  # L1 button
    enable_turbo_button: 5  # R1 button

    

    